#Controls general gamemode settings. Individual settings have their own descriptions.
settings:
  #Controls the name of the world you wish to use as a lobby.
  lobby: "lobby"
  #Controls the coordinates of a universal spawn point of the lobby world.
  #Coordinates are strings written like this: X:Y:Z:pitch:yaw, where : is the separator which should be included between values.
  lobby-spawn: "100.0:64.0:100.0:0.0f:0.0f" #Example coordinates
  #Controls the name of the world you wish to use as a Hunger Games arena.
  arena: "arena"
  #Controls arena spawn spots.
  #Coordinates are presented in a form of a list, chosen first to last and assigned to players in join order.
  #Coordinates are strings written like this: X:Y:Z:pitch:yaw, where : is the separator which should be included between values.
  #In order for pitch and yaw to work as intended, please put an 'f' in the end of the value.
  arena-spawns:
    - "100.0:64.0:100.0:0.0f:0.0f" #Example coordinates
    - "110.0:64.0:100.0:180.0f:0.0f" #Example coordinates
  #Controls the center of the arena (at the cornucopia). Used for setting a world border.
  arena-center: "100.0:100.0" #Example arena center: "100.0:100.0"
  #Controls the radius of the world border.
  world-border-radius: 50
#Controls messages output by the plugin.
#Placeholders provided in existing messages only work with these messages.
messages:
  prefix: "&e&lHungerGames &8| &r"
  no-permission: "&cYou do not have permission to perform this command."
  game-started: "&fGame has successfully started!"
  lobby-timer-notifications: "&fVoting concludes in {timer} {m}!"
  launch-cancelled: "&fNot enough players for the game to start! Timer aborted."
  global-timer-notifications: "&fThe game will commence in {timer} {m}!"
  global-game-started: "&fGame is now commencing!"
  grace-period: "&fGrace period will end in {timer} {m}!"
  grace-period-ended: "&fGrace period has ended!"
  global-kill: "&fA cannon can be heard in the distance. Only {players} players remain!"
  kill: "&fYou have eliminated &e{player}&f!"
  killed: "&fYou were eliminated by &e{player}&f!"
  killed-natural: "&fYou were eliminated!"
  deathmatch-timer-notifications: "&fDeathmatch will begin in {timer} {m}!"
  deathmatch-started: "&fDeathmatch is now commencing!"
  deathmatch-prepare: "&fYou have {timer} {m} to prepare for the deathmatch!"
  victory: "&eYou are the winner of the Hunger Games!"
  victory-title: "&6&lVICTORY!"
  victory-global: "&e{player} &fhas won the Hunger Games!"
  endgame: "&fThe server will restart in {timer} {m}."
  refill: "&fAll chests will be refilled in {timer} {m}!"
  refill-commencing: "&fAll chests have been refilled!"
  summary:
    - "Game summary is coming soon!"
    - "It will be broadcasted once the game is over"
    - "And will feature a full-fledged kill leaderboard!"