name: YAGHGP
main: ru.dgrew.yaghgp.Main
version: '${project.version}'
api-version: 1.13
authors: [ DGrew, rodent567 ]
description: Yet Another Generic Hunger Games Plugin
commands:
  start:
    description: "/start - Starts a Hunger Games session for all online players."
  vote:
    description: "/vote - Vote on random map or custom map."