name: MC-HG
main: com.au.lachysh.mchg.Main
version: '${project.version}'
api-version: 1.13
authors: [ DGrew, rodent567 ]
description: MC-HG
commands:
  start:
    description: "/start - Starts a Hunger Games session for all online players."
  vote:
    description: "/vote - Vote on random map or custom map."
  endvote:
    description: "/endvote - End voting time and start game shortly after."
  nextphase:
    description: "/nextphase - For admin / debug use only. Force the next phase of the match."
  kits:
    description: "/kits - Opens the kit selection UI"
  writeitem:
    description: "/writeitem - For admin / debug use only. Write the item in hand to yaml for starting-items usage"
